# -*- coding: utf-8 -*-
"""2430506056_TugasStrukturData_Array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFekakL1YEkkreKCcpZHqMCjdkyHaJso
"""

size = 10

treasure_map = ["_" for _ in range(size)]

print(f"Selamat datang di Treasure Hunt! Peta memiliki {size} lokasi (0 hingga {size-1}).")

treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}) :"))
while treasure_index < 0 or treasure_index >= size:
    print("Lokasi tidak valid. Silakan coba lagi.")
    treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}) :"))

treasure_map[treasure_index] = "X"

def play_treasure_hunt():
  print("\nHarta Karun telah disembunyikan! Sekarang giliran pemain menebak.")
  print("Cobalah untuk menemukan harta karun dengan menebak indeks yang benar.")

  while True:
    print("\nPeta saat ini: ", ["_" for _ in range(size)])

    try:
      guess = int(input(f"Masukkan indeks tebakanmu (0-{size-1}): "))
    except ValueError:
      print("Masukkan angka yang valid!")
      continue
    if guess < 0 or guess >= size:
      print("Indeks tidak valid, pilih anatara 0 hingga", size-1)
      continue
    if treasure_map[guess] == "X":
      print("Selamat! Kamu menemukan harta karun di lokasi:", guess)
      break
    else:
      print("Tidak ada harta di lokasi ini. Coba lagi!")

  print("Terima kasih sudah bermain!")

play_treasure_hunt()

def play_treasure_hunt(size, treasure_map):
    print("\nHarta Karun telah disembunyikan! Sekarang giliran pemain menebak.")
    while True:
        print("\nPeta saat ini:", ["_"] * size)
        guess = int(input(f"Masukkan indeks tebakanmu (0-{size-1}): "))
        if guess < 0 or guess >= size:
            print("Indeks tidak valid, pilih antara 0 hingga", size-1)
            continue
        if treasure_map[guess] == "X":
            print("Selamat! Kamu menemukan harta karun di lokasi:", guess)
            break
        else:
            print("Tidak ada harta di lokasi ini. Coba lagi!")
    print("Terima kasih sudah bermain!")

size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))
while size < 2:
    print("Ukuran peta harus minimal 2.")
    size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))

treasure_map = ["_"] * size
print(f"Selamat datang di Treasure Hunt! Peta memiliki {size} lokasi (0 hingga {size-1}).")

treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}): "))
while treasure_index < 0 or treasure_index >= size:
    print("Lokasi tidak valid. Silakan coba lagi.")
    treasure_index = int(input(f"Masukkan lokasi harta karun (0-{size-1}): "))

treasure_map[treasure_index] = "X"

play_treasure_hunt(size, treasure_map)

import random

def play_treasure_hunt(size, treasure_map):
    print("\nHarta Karun telah disembunyikan! Sekarang giliran pemain menebak.")
    while True:
        print("\nPeta saat ini:", ["_"] * size)
        guess = int(input(f"Masukkan indeks tebakanmu (1-{size}): ")) - 1
        if guess < 0 or guess >= size:
            print("Indeks tidak valid, pilih antara 1 hingga", size)
            continue
        if treasure_map[guess] == "X":
            print("Selamat! Kamu menemukan harta karun di lokasi:", guess + 1)
            break
        else:
            print("Tidak ada harta di lokasi ini. Coba lagi!")
    print("Terima kasih sudah bermain!")

size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))
while size < 2:
    print("Ukuran peta harus minimal 2.")
    size = int(input("Masukkan ukuran peta yang diinginkan (minimal 2): "))

treasure_map = ["_"] * size
print(f"Selamat datang di Treasure Hunt! Peta memiliki {size} lokasi (1 hingga {size}).")

treasure_index = random.randint(0, size - 1)
print(f"Harta karun telah disembunyikan secara otomatis!")
8
treasure_map[treasure_index] = "X"

play_treasure_hunt(size, treasure_map)